spring:
  thymeleaf:
    cache: false

  webflux:
    hiddenmethod:
      filter:
        enabled: true

  r2dbc:
    username: postgres
    password: 1111
    url: r2dbc:pool:postgresql://127.0.0.1:5432/test

  # multi db 설정 참고 : https://velog.io/@ddclub12/Spring-webflux-muliti-database-Trasactional-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0
  # data:
  #  mongodb:
  #    uri: mongodb://127.0.0.1:27017/cart
  #    username:
  #    password:

logging:
  level:
    org.springframework.r2dbc.core: debug
