spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/test
    username: postgres
    password: 1111

  webflux:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    org.springframework.r2dbc: DEBUG

debug: true


